M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu20.04.1} date Mon 11 Mar 2024 21:24:20 CST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-11T21:24:20+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X181.45Y-92.95
X184.45Y-92.95
T2
X192.25Y-73.5
X192.25Y-84.25
T3
X174.5Y-55.0
X174.5Y-92.0
X211.5Y-55.0
X211.5Y-92.0
M30
